import StepOne from "./StepOne";
import StepTwo from "./StepTwo";
import StepThree from "./StepThree";
import StepFour from "./StepFour";

export { StepOne, StepTwo, StepThree, StepFour };
export  const units = {
    length: ["Meter (m)", "Yard (yd)"],
    area: ["Square Meter (sqm)", "Square Foot (sqft)", "Square Yard (sqyd)"],
    volume: ["Cubic Meter (cum)"],
    weight: ["Kilogram (kg)", "Metric Ton (MT)"],
    runningLength: ["Running Meter (rsm)"],
  };
export  const items = [
    "Excavation (manual)",
    "Excavation (machine)",
    "Backfilling with soil",
    "Earth compaction",
    "Grading",
    "Leveling",
    "Site clearing",
    "Plain Cement Concrete (PCC)",
    "Reinforced Cement Concrete (RCC)",
    "Shuttering/Formwork",
    "Steel Reinforcement (TMT Bars)",
    "Footings",
    "Pile foundations",
    "Retaining walls",
    "Slabs",
    "Clay Brick Masonry (9 wall)",
    "Fly Ash Brick Masonry",
    "AAC Block Masonry",
    "Internal Cement Plaster (12mm)",
    "External Plaster (20mm)",
    "POP/Putty Finishing",
    "Vitrified Tiles Flooring (600x600mm)",
    "Ceramic Wall Tiles (300x450mm)",
    "Marble/Granite Flooring",
    "RCC Roof Slab (M20 grade)",
    "Bituminous Waterproofing",
    "Polyurethane (PU) Coating",
    "Treatments",
    "Interior Emulsion Paint (Asian/Berger)",
    "Exterior Weatherproof Paint",
    "Enamel Paint (Doors, Windows, Metal)",
    "Mild Steel Structural Fabrication",
    "Stainless Steel Fabrication",
    "Industrial sheds",
    "Trusses",
    "Bituminous (Asphalt) Road",
    "Concrete Road (RCC M30 grade)",
    "Paver Block Roads",
    "Additional Works",
    "Scaffolding Rental",
    "Labour Charges (Mason, Carpenter, Painter)",
    "Borewell Drilling (150mm - 250mm dia)",
    "Fireworks",
    "Heating",
    "Gardening",
    "Glazing",
  ]; // Dropdown items